Dodano podstawowe wyświetlanie listy roślin na stronie głównej
Pokrzw/Plant-Tracker pull request #24
Opened 2024-12-01 15:50 UTC by JagnaJuras

Wyświetlanie listy. Elementy da się kliknąć, w następnym branchu będę ogarniać widok detali dla poszczególnych roślin.

Modifiery narazie są zakodowane w komponencie, w jakimś kolejnym issue przeniosę wszystkie elementy związane z wyglądem do osobnych plików, żeby były reusable.

Trzeba przetestować, czy lista jest reaktywna (czy nowe pozycje wyświetlają się po dodaniu ich).

2024-12-01 22:59 UTC, Pokrzw requested changes
Sprawdzalam na telefonie, dobrze dziala, tylko 2 sugestie zostawilam

2024-12-01 22:59 UTC, Pokrzw commented on frontend/app/src/main/java/com/example/planttrackerapp/ui/components/SinglePlantCard.kt
> +}
Mysle, ze moznaby dodac preview:
`
@Preview(showBackground=true)
@Composable
fun PreviewSingleCard(){
    SinglePlantCard(plant = Datasource.plantList[0], onItemClick = {})
}
`

2024-12-01 22:59 UTC, Pokrzw commented on frontend/app/src/main/java/com/example/planttrackerapp/ui/PlantList.kt
>      }
Jakbys pod ta lista mogla dodac jakis button co onClick by mial onClickB, zeby bylo mozna z tego widoku potem testowac formularz

2024-12-02 09:29 UTC, JagnaJuras commented on frontend/app/src/main/java/com/example/planttrackerapp/ui/components/SinglePlantCard.kt
> +}
Dodane

2024-12-02 09:29 UTC, JagnaJuras commented on frontend/app/src/main/java/com/example/planttrackerapp/ui/PlantList.kt
>      }
Dodane

2024-12-02 10:08 UTC, Pokrzw approved these changes

2024-12-02 10:08 UTC, merged